/** ClinicFlow Google Apps Script backend. MVP/public-booking API. Do not use for real clinical records without proper authentication/compliance controls. */
const CF={clinicName:'ClinicFlow',timezone:'Africa/Khartoum',spreadsheetName:'ClinicFlow Database',sheets:{patients:'Patients',appointments:'Appointments',doctors:'Doctors',payments:'Payments',audit:'AuditLog'}};
const HEADERS={Patients:['Patient ID','Name','Phone','Created At','Updated At'],Appointments:['Appointment ID','Patient ID','Patient Name','Phone','Doctor ID','Doctor Name','Specialty','Date','Time','Reason','Status','Created At','Updated At'],Doctors:['Doctor ID','Name','Specialty','Duration','Working Days','Start Time','End Time','Active'],Payments:['Receipt No','Appointment ID','Patient ID','Amount','Currency','Method','Status','Created At'],AuditLog:['Timestamp','Action','Actor','Record ID','Details']};
function setupClinicFlow(){const p=PropertiesService.getScriptProperties();let ss;const id=p.getProperty('CLINICFLOW_SPREADSHEET_ID');if(id)ss=SpreadsheetApp.openById(id);else{ss=SpreadsheetApp.create(CF.spreadsheetName);p.setProperty('CLINICFLOW_SPREADSHEET_ID',ss.getId());}Object.keys(HEADERS).forEach(n=>ensureSheet_(ss,n,HEADERS[n]));seedDoctors_(ss);Logger.log('Spreadsheet: '+ss.getUrl());return{success:true,spreadsheetId:ss.getId(),spreadsheetUrl:ss.getUrl()};}
function doGet(e){try{const a=String((e&&e.parameter&&e.parameter.action)||'health');if(a==='health')return json_({success:true,service:CF.clinicName,version:'1.0.0'});if(a==='doctors')return json_({success:true,doctors:getDoctors_()});if(a==='slots'){const d=String(e.parameter.doctorId||''),date=String(e.parameter.date||'');return json_({success:true,doctorId:d,date,slots:getAvailableSlots_(d,date)});}return json_({success:false,error:'Unknown action'});}catch(err){return json_({success:false,error:String(err.message||err)});}}
function doPost(e){try{const b=parseBody_(e);if(String(b.action||'')==='bookAppointment')return json_(bookAppointment_(b.data||{}));return json_({success:false,error:'Unknown action'});}catch(err){return json_({success:false,error:String(err.message||err)});}}
function bookAppointment_(d){const name=clean_(d.name),phone=clean_(d.phone),doctorId=clean_(d.doctorId),date=clean_(d.date),time=clean_(d.time),reason=clean_(d.reason||'Consultation');if(!name||!phone||!doctorId||!date||!time)throw Error('Name, phone, doctor, date and time are required.');if(!/^\d{4}-\d{2}-\d{2}$/.test(date)||!/^\d{2}:\d{2}$/.test(time))throw Error('Invalid appointment date or time.');const doctor=getDoctors_().find(x=>x.id===doctorId&&x.active);if(!doctor)throw Error('Doctor not found or inactive.');const day=new Date(date+'T12:00:00').getDay();if(!doctor.days.includes(day))throw Error('Doctor does not work on this day.');if(!doctor.slots.includes(time))throw Error('Invalid slot for this doctor.');const lock=LockService.getScriptLock();lock.waitLock(10000);try{const s=getDb_().getSheetByName(CF.sheets.appointments),v=s.getDataRange().getValues(),h=v.shift()||[],di=h.indexOf('Doctor ID'),da=h.indexOf('Date'),ti=h.indexOf('Time'),st=h.indexOf('Status');if(v.some(r=>String(r[di])===doctorId&&formatDate_(r[da])===date&&String(r[ti])===time&&String(r[st]).toLowerCase()!=='cancelled'))throw Error('That appointment slot is already booked.');const now=new Date(),p=findOrCreatePatient_(name,phone,now),id=nextId_('APT');s.appendRow([id,p.id,name,phone,doctor.id,doctor.name,doctor.specialty,date,time,reason,'confirmed',now,now]);audit_('BOOK_APPOINTMENT',id,JSON.stringify({doctorId,date,time}));return{success:true,appointmentId:id,patientId:p.id,doctor:doctor.name,specialty:doctor.specialty,date,time,status:'confirmed'};}finally{lock.releaseLock();}}
function getDoctors_(){const v=getDb_().getSheetByName(CF.sheets.doctors).getDataRange().getValues();v.shift();return v.filter(r=>r[0]).map(r=>{const days=String(r[4]||'').split(',').map(Number).filter(x=>!isNaN(x)),duration=Number(r[3])||30;return{id:String(r[0]),name:String(r[1]),specialty:String(r[2]),duration,days,start:String(r[5]),end:String(r[6]),active:String(r[7]).toLowerCase()!=='false',slots:buildSlots_(String(r[5]),String(r[6]),duration)};});}
function getAvailableSlots_(doctorId,date){const d=getDoctors_().find(x=>x.id===doctorId&&x.active);if(!d||!date)return[];const day=new Date(date+'T12:00:00').getDay();if(!d.days.includes(day))return[];const v=getDb_().getSheetByName(CF.sheets.appointments).getDataRange().getValues(),h=v.shift()||[],di=h.indexOf('Doctor ID'),da=h.indexOf('Date'),ti=h.indexOf('Time'),st=h.indexOf('Status');const booked=new Set(v.filter(r=>String(r[di])===doctorId&&formatDate_(r[da])===date&&String(r[st]).toLowerCase()!=='cancelled').map(r=>String(r[ti])));return d.slots.map(time=>({time,available:!booked.has(time)}));}
function findOrCreatePatient_(name,phone,now){const s=getDb_().getSheetByName(CF.sheets.patients),v=s.getDataRange().getValues();v.shift();for(let i=0;i<v.length;i++)if(String(v[i][2]).trim()===phone){const id=String(v[i][0]);s.getRange(i+2,2).setValue(name);s.getRange(i+2,5).setValue(now);return{id,name,phone};}const id=nextId_('PAT');s.appendRow([id,name,phone,now,now]);return{id,name,phone};}
function nextId_(prefix){const p=PropertiesService.getScriptProperties(),k='SEQ_'+prefix,n=Number(p.getProperty(k)||0)+1;p.setProperty(k,String(n));return prefix+'-'+Utilities.formatDate(new Date(),CF.timezone,'yyyyMMdd')+'-'+String(n).padStart(4,'0');}
function seedDoctors_(ss){const s=ss.getSheetByName(CF.sheets.doctors);if(s.getLastRow()>1)return;s.getRange(2,1,3,8).setValues([['DOC-001','Dr. Sara Ahmed','General Medicine',30,'1,2,3,4,5','09:00','15:00',true],['DOC-002','Dr. Mohamed Ali','Dermatology',30,'0,2,4','10:00','17:00',true],['DOC-003','Dr. Huda Osman','Dental',45,'1,3,5','09:00','13:00',true]]);}
function ensureSheet_(ss,name,headers){let s=ss.getSheetByName(name);if(!s)s=ss.insertSheet(name);if(s.getLastRow()===0)s.getRange(1,1,1,headers.length).setValues([headers]);s.setFrozenRows(1);s.getRange(1,1,1,headers.length).setFontWeight('bold');return s;}
function buildSlots_(start,end,duration){const out=[];let cur=toMinutes_(start),finish=toMinutes_(end);while(cur+duration<=finish){out.push(minutesToTime_(cur));cur+=duration;}return out;}
function toMinutes_(v){const p=String(v).split(':').map(Number);return(p[0]||0)*60+(p[1]||0);}
function minutesToTime_(m){return String(Math.floor(m/60)).padStart(2,'0')+':'+String(m%60).padStart(2,'0');}
function formatDate_(v){if(v instanceof Date)return Utilities.formatDate(v,CF.timezone,'yyyy-MM-dd');const s=String(v||'');return s.length>=10?s.slice(0,10):s;}
function clean_(v){return String(v==null?'':v).trim().slice(0,500);}
function getDb_(){const id=PropertiesService.getScriptProperties().getProperty('CLINICFLOW_SPREADSHEET_ID');if(!id)throw Error('Run setupClinicFlow() first.');return SpreadsheetApp.openById(id);}
function parseBody_(e){if(!e||!e.postData||!e.postData.contents)return{};try{return JSON.parse(e.postData.contents);}catch(_){return{};}}
function audit_(action,id,details){getDb_().getSheetByName(CF.sheets.audit).appendRow([new Date(),action,'public-web',id,details]);}
function json_(o){return ContentService.createTextOutput(JSON.stringify(o)).setMimeType(ContentService.MimeType.JSON);}
